export const CREATE_USER_REQUEST = 'CREATE_USER_REQUEST';
export const USER_LOGGED_IN = 'USER_LOGGED_IN';
export const CREATE_USER_ERRORS = 'CREATE_USER_ERRORS';
export const LOGIN_USER_REQUEST = 'LOGIN_USER_REQUEST';
