sudo: false
language: node_js
node_js:
- '8'
branches:
  only:
  - feature/serveur/signup
cache:
  directories:
  - node_modules
before_install:
- npm update
install:
- npm ci
script:
- npm test
- npm run coveralls

notification:
  email:false